language: r
cache: packages
latex: false
warnings_are_errors: false
r_build_args: 
r_check_args: --as-cran

r_packages:
  - covr

# This is the minimal set of R packages needed to run "R CMD check" on
# the package.
install:
  - R -e 'install.packages(c("testthat","Rcpp","RcppArmadillo","remotes","rmarkdown","knitr","covr"))'
  - R -e 'remotes::install_github("stephenslab/mr.ash.alpha",upgrade="never",force=TRUE)'  
env:
  global:
    - _R_CHECK_FORCE_SUGGESTS_: false
    - R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

after_success:
  - Rscript -e 'covr::codecov()'

branches:
  only:
    - master
